---
- name: Creer le repertoire cible
  file:
    path: "{{ target_dir }}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: www-data
    group: www-data
  tags: webapp

- name: Deployer le fichier index.html
  template:
    src: index.html-base.j2
    dest: "{{ target_dir }}/index.html"
    mode: '0644'
    owner: www-data
    group: www-data
  tags: webapp

- name: Installer unzip
  package:
    name: unzip
    state: latest
  tags: webapp

- name: Creer le repertoire playbook_stacker
  file:
    path: "{{ target_dir }}/playbook_stacker"
    state: directory
    recurse: yes
    mode: '0755'
    owner: www-data
    group: www-data
  tags: webapp

- name: Deployer le jeu Playbook Stacker
  unarchive:
    src: "{{ role_path }}/files/playbook_stacker.zip"
    dest: "{{ target_dir }}/playbook_stacker"
    remote_src: no
    mode: '0755'
    owner: www-data
    group: www-data
  tags: webapp

- name: Pull de l image Docker pour la webapp
  docker_image:
    name: nginx
    tag: latest
    source: pull
  tags: webapp

- name: Lancer le conteneur webapp
  docker_container:
    name: "{{ container_name }}"
    image: nginx:latest
    state: started
    restart_policy: always
    networks:
      - name: custom_net
    volumes:
      - "{{ target_dir }}:/usr/share/nginx/html:ro"
  tags: webapp
